# -*- coding: utf-8 -*-
"""Simple LDA System.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1co17SeoPt6oVUMFph_PLVTol8lf6eMsw
"""

# Import libraries
import gensim
from gensim import corpora

# Create data
documents = [['apple', 'banana', 'fruits'], ['bought', 'bicycle', 'recently', 'less', 'two', 'years', 'buy', 'bike'], 
             ['colour', 'apple', 'bicycle', 'red']]
mapping = corpora.Dictionary(documents)
data = [mapping.doc2bow(word) for word in documents]

# Print data
data

# Train LDA model
ldamodel = gensim.models.ldamodel.LdaModel(data, num_topics=2, id2word=mapping, passes=15)

# Show topics
topics = ldamodel.show_topics()
print(topics)

# Distribution of topics for the first document
print(ldamodel.get_document_topics(data[0]))